.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitmonkey_qt test_bitmonkey_qt
clean: FORCE
	$(MAKE) -C .. bitmonkey_qt_clean test_bitmonkey_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitmonkey_qt_check
bitmonkey-qt bitmonkey-qt.exe: FORCE
	 $(MAKE) -C .. bitmonkey_qt
